### ISSUE TITLE
[suggestion] Format chapter number to %03d

### ISSUE THREAD

**Issue by kuanyui** [eight04/ComicCrawler#22]
For sorting.

**Comment by eight04** [comment]
Comic Crawler doesn't know the chapter number but the title (although it contains the chapter number in most cases). It is hard to extract chapter number from the title.

It would be better to format the title str in site modules, but I doubt if we should do that since the title is directly grabbed from the web page.

**Comment by eight04** [comment]
👍 
Would you like to send a PR for this?
https://github.com/eight04/ComicCrawler/blob/master/comiccrawler/mods/dm5.py#L34

**Comment by eight04** [comment]
Fixed in 2017.1.6.
